# services/stt-provider/Dockerfile

FROM python:3.12-slim as builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

WORKDIR /app

# Copy scaffolded Docker build context (created by scripts/scaffold_context.py)
# This includes: uv.lock, pyproject.toml, and all service/lib pyproject.toml files
COPY .docker-context/ ./

# Sync dependencies
RUN uv sync --frozen --no-install-project --package stt-provider

FROM python:3.12-slim
WORKDIR /app

# Copy venv
COPY --from=builder /app/.venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

# Copy shared libs
COPY libs/messaging ./libs/messaging

# Copy service code
COPY services/stt-provider ./services/stt-provider

# Install project
# RUN uv sync --frozen --package stt-provider

ENV PYTHONPATH="/app/services/stt-provider/src:/app/libs/messaging/src:$PYTHONPATH"
CMD ["python", "-m", "stt_provider.main"]
