#!/usr/bin/env python3
"""
Generate .dockerignore

This script generates a `.dockerignore` file to prevent platform-specific artifacts
(Windows/Mac local environments) from corrupting Linux container builds.

Usage:
    python scripts/generate_dockerignore.py
"""

from __future__ import annotations

from pathlib import Path


def generate_dockerignore() -> None:
    """Generate .dockerignore file at repository root."""
    repo_root = Path(__file__).parent.parent
    dockerignore_path = repo_root / ".dockerignore"

    # Define patterns to exclude from Docker build context
    ignore_patterns = [
        "# =============================================================================",
        "# Auto-generated by scripts/generate_dockerignore.py",
        "# DO NOT EDIT MANUALLY - Run 'python scripts/generate_dockerignore.py'",
        "# to regenerate",
        "# =============================================================================",
        "",
        "# Python artifacts (platform-specific)",
        "__pycache__/",
        "*.py[cod]",
        "*$py.class",
        "*.so",
        ".Python",
        "",
        "# Virtual environments (host machine specific)",
        ".venv/",
        "venv/",
        "env/",
        "ENV/",
        "env.bak/",
        "venv.bak/",
        "",
        "# Testing and coverage",
        ".pytest_cache/",
        ".coverage",
        "htmlcov/",
        ".tox/",
        ".nox/",
        "",
        "# Type checking and linting caches",
        ".mypy_cache/",
        ".ruff_cache/",
        ".dmypy.json",
        "dmypy.json",
        "",
        "# Build artifacts",
        "build/",
        "dist/",
        "*.egg-info/",
        ".eggs/",
        "",
        "# IDE and OS files",
        ".vscode/",
        ".idea/",
        ".DS_Store",
        "Thumbs.db",
        "*.swp",
        "*.swo",
        "",
        "# Git",
        ".git/",
        ".gitignore",
        ".gitattributes",
        "",
        "# Environment and secrets",
        ".env",
        ".env.*",
        "secrets/",
        "",
        "# Data volumes (should be mounted, not copied)",
        "data/",
        "",
        "# Documentation and CI (not needed in runtime containers)",
        "docs/",
        ".github/",
        "*.md",
        "!README.md",
        "",
        "# Package manager artifacts",
        ".pdm-build/",
        ".pdm-python",
        "",
        "# Misc",
        "*.log",
        ".copier-answers.yml",
        "",
        "# IMPORTANT: Do NOT exclude .docker-context/ - it's needed for the build!",
        "# .docker-context/",
    ]

    # Write to .dockerignore
    with dockerignore_path.open("w", encoding="utf-8") as f:
        f.write("\n".join(ignore_patterns))
        f.write("\n")

    print(f"✅ Generated {dockerignore_path}")


if __name__ == "__main__":
    generate_dockerignore()
